// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwbKoE1eI2pn5modqEzvm4VqeHAAYg-xo',
    appId: '1:386802192266:web:c838935b17cbe2f0f70273',
    messagingSenderId: '386802192266',
    projectId: 'project2-80c40',
    authDomain: 'project2-80c40.firebaseapp.com',
    storageBucket: 'project2-80c40.firebasestorage.app',
    measurementId: 'G-VGLVRPN8GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHDIahNz2dO5wObpJfYDY9c6l2p8u04SI',
    appId: '1:386802192266:android:86305f8c03f00bfdf70273',
    messagingSenderId: '386802192266',
    projectId: 'project2-80c40',
    storageBucket: 'project2-80c40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWsHMdnZV3uVWqZf9vcq-mRGKesix8o6E',
    appId: '1:386802192266:ios:93bc7574461568fdf70273',
    messagingSenderId: '386802192266',
    projectId: 'project2-80c40',
    storageBucket: 'project2-80c40.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWsHMdnZV3uVWqZf9vcq-mRGKesix8o6E',
    appId: '1:386802192266:ios:93bc7574461568fdf70273',
    messagingSenderId: '386802192266',
    projectId: 'project2-80c40',
    storageBucket: 'project2-80c40.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwbKoE1eI2pn5modqEzvm4VqeHAAYg-xo',
    appId: '1:386802192266:web:c80bd1f150b58708f70273',
    messagingSenderId: '386802192266',
    projectId: 'project2-80c40',
    authDomain: 'project2-80c40.firebaseapp.com',
    storageBucket: 'project2-80c40.firebasestorage.app',
    measurementId: 'G-2D0DVBLYBQ',
  );
}
